### ISSUE TITLE
Refactor the maze drawing and implement new mazes

### ISSUE THREAD

**Issue by asas1asas200** [YiKaiWu1125/ElecTrap_backend#4]
+ Refactor the maze drawing
+ Add new mazes
+ Add new mazes from video

**Comment by fcebk17** [comment]
Please create at least 1 maze in each game mode. @YiKaiWu1125 
game mode (total : 6):
warm up - hands
warm up - head 
warm up - foot 
master - hands
master - head
master - foot

**Comment by fcebk17** [comment]
Set parameters in all mazes @YiKaiWu1125 
- game_level = 1 (int)
- game_mode = warmup  || game_mode = master
- game_body = hands || game_body = foot || game_body = head
- score = 秒數 (遊戲花費時間，儲存到小數點後第三位)

**Comment by YiKaiWu1125** [comment]
@asas1asas200 可以教我如何 `Refactor code` 嗎 ，我好像沒有啥頭緒QQ

**Comment by asas1asas200** [comment]
Don't repeat the code like this: [f99746a](https://github.com/YiKaiWu1125/ElecTrap_backend/commit/f99746a53bd00353c8e58b5f3b3136cb2aa6fa0e).
Consider adding a new mode in `mediapipe_processor.py` and `solution.py` and write/rewrite a new function if needed.

The `Processor` class can be more clear:
+ What is `self.sta`, `self.r_string`? Give them a clear name like `status`.
+ The `init_val()` function in `__init__()` is unneeded, remove it and the `r_init_val()` function in `parse()`. You can write a function like `reset()` in class and call it in `__init__()` and anytime you want to reset the object.

You can read some concepts in this [Clean Code 無瑕的程式碼 | 閱讀筆記](https://medium.com/%E6%89%8B%E5%AF%AB%E7%AD%86%E8%A8%98/clean-code-index-51e209cc47db).
The most important is reading the books talking about refactoring, and reading more codes.
Try to understand what the code doing and why the code writing as this, don't just copy-paste.
